/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: "1.5rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        display: ['system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        body: ['system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
        mono: ['ui-monospace', 'SFMono-Regular', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'],
      },
      fontSize: {
        'hero-display': ['64px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-1px' }],
        'display-lg': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.5px' }],
        'display-md': ['40px', { lineHeight: '1.15', fontWeight: '600', letterSpacing: '-0.3px' }],
        'display-sm': ['32px', { lineHeight: '1.2', fontWeight: '600', letterSpacing: '0' }],
        'title-lg': ['24px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '0' }],
        'title-md': ['20px', { lineHeight: '1.35', fontWeight: '600', letterSpacing: '0' }],
        'title-sm': ['16px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0' }],
        'number-display': ['40px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.3px' }],
        'number-md': ['16px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0' }],
        'number-sm': ['14px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400', letterSpacing: '0' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0' }],
        'btn': ['14px', { lineHeight: '1', fontWeight: '600', letterSpacing: '0' }],
        'nav-link': ['14px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0' }],
      },
      colors: {
        primary: '#fcd535',
        'primary-active': '#f0b90b',
        'primary-disabled': '#3a3a1f',
        ink: '#181a20',
        body: '#eaecef',
        'body-on-light': '#181a20',
        muted: '#707a8a',
        'muted-strong': '#929aa5',
        'hairline-on-light': '#eaecef',
        'hairline-on-dark': '#2b3139',
        'border-strong': '#cdd1d6',
        'canvas-light': '#ffffff',
        'canvas-dark': '#0b0e11',
        'surface-card-dark': '#1e2329',
        'surface-elevated-dark': '#2b3139',
        'surface-soft-light': '#fafafa',
        'surface-strong-light': '#f5f5f5',
        'on-primary': '#181a20',
        'on-dark': '#ffffff',
        'trading-up': '#0ecb81',
        'trading-down': '#f6465d',
        'accent-turquoise': '#2dbdb6',
        info: '#3b82f6',
      },
      spacing: {
        'xxs': '4px',
        'xs': '8px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'xxl': '48px',
        'section': '80px',
      },
      borderRadius: {
        'xs': '2px',
        'sm': '4px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
        'pill': '9999px',
        'full': '9999px',
      },
    },
  },
  plugins: [
    require("tailwindcss-animate"),
    require('@tailwindcss/typography'),
  ],
}
