'use client';

import { useState, useEffect, useMemo } from 'react';
import axios from 'axios';
import { Lock, Eye, EyeOff, UserPlus, FileText, Users, LogOut, Filter, X, Calendar, Megaphone, Trash2, RefreshCw, CheckCircle, XCircle, Edit, ChevronDown, ChevronUp, MessageSquare, Search, Shield, Bell as BellIcon } from 'lucide-react';
import { CreateNotification } from '@/components/admin/CreateNotification';

export default function AdminConsole() {
  const [token, setToken] = useState(''); const [isAuthenticated, setIsAuthenticated] = useState(false); const [loading, setLoading] = useState(true);
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [loginError, setLoginError] = useState('');
  const [view, setView] = useState('users'); const [users, setUsers] = useState([]); const [logs, setLogs] = useState([]);
  const [newUser, setNewUser] = useState({ handle: '', leetcodeHandle: '', atcoderHandle: '', codechefHandle: '' }); const [actionLoading, setActionLoading] = useState(false);
  const [userSearch, setUserSearch] = useState(''); const [nicknameEditorOpen, setNicknameEditorOpen] = useState(false); const [editingUser, setEditingUser] = useState(null);
  const [nicknameForm, setNicknameForm] = useState({ newHandle: '', leetcodeHandle: '', atcoderHandle: '', codechefHandle: '' }); const [nicknameSaving, setNicknameSaving] = useState(false);
  const [featureFlags, setFeatureFlags] = useState({ atcoderSubmissions: false }); const [featureSaving, setFeatureSaving] = useState(false);
  const [filters, setFilters] = useState({ ip: '', method: '', endpoint: '', startDate: '', endDate: '' }); const [activeFilters, setActiveFilters] = useState({});
  const [auditViewMode, setAuditViewMode] = useState('ip'); const [auditSummary, setAuditSummary] = useState([]);
  const [expandedIp, setExpandedIp] = useState(null); const [ipLogs, setIpLogs] = useState([]); const [loadingIpLogs, setLoadingIpLogs] = useState(false);
  const [adminActionsOnly, setAdminActionsOnly] = useState(false); const [chatSummary, setChatSummary] = useState([]);
  const [currentBanner, setCurrentBanner] = useState(null); const [bannerMsg, setBannerMsg] = useState(''); const [bannerType, setBannerType] = useState('info'); const [bannerDuration, setBannerDuration] = useState(24);
  const [backfilling, setBackfilling] = useState(false); const [backfillResult, setBackfillResult] = useState(null);

  const API = () => process.env.NEXT_PUBLIC_API_URL || 'http://localhost:3001/api';
  useEffect(() => { const s = localStorage.getItem('admin_token'); if (s) { setToken(s); setIsAuthenticated(true); fetchAll(s) } else setLoading(false) }, []);
  const fetchAll = async (t) => { setLoading(true); try { if (view === 'users') { await fetchUsers(t); await fetchFlags(t) } else if (view === 'audit') { if (auditViewMode === 'ip') await fetchSummary(t); else await fetchLogs(t, {}) } else if (view === 'announcements') await fetchBanner(t); else if (view === 'chat') await fetchChat(t) } catch (e) { if (e.response?.status === 401) logout() } finally { setLoading(false) } };
  useEffect(() => { if (isAuthenticated && token) { if (view === 'users') { fetchUsers(token); fetchFlags(token) } if (view === 'audit') { if (auditViewMode === 'ip') fetchSummary(token); else fetchLogs(token, activeFilters) } if (view === 'announcements') fetchBanner(token); if (view === 'chat') fetchChat(token) } }, [view, auditViewMode]);
  const logout = () => { localStorage.removeItem('admin_token'); setToken(''); setIsAuthenticated(false); setUsers([]); setLogs([]) };
  const fetchUsers = async (t) => { try { const r = await axios.get(`${API()}/admin/users`, { headers: { Authorization: `Bearer ${t}` } }); setUsers(r.data.data) } catch (_) {} };
  const fetchFlags = async (t) => { try { const r = await axios.get(`${API()}/admin/feature-flags`, { headers: { Authorization: `Bearer ${t}` } }); setFeatureFlags({ atcoderSubmissions: !!r.data?.data?.atcoderSubmissions }) } catch (_) {} };
  const fetchLogs = async (t, f) => { try { const p = new URLSearchParams(); ['ip','method','startDate','endDate'].forEach(k => { if (f[k]) p.append(k, f[k]) }); const r = await axios.get(`${API()}/admin/audit-logs?${p}`, { headers: { Authorization: `Bearer ${t}` } }); setLogs(r.data.data) } catch (_) {} };
  const fetchSummary = async (t) => { setLoading(true); try { const r = await axios.get(`${API()}/admin/audit-summary`, { headers: { Authorization: `Bearer ${t}` } }); setAuditSummary(r.data.data) } catch (_) {} finally { setLoading(false) } };
  const fetchChat = async (t) => { setLoading(true); try { const r = await axios.get(`${API()}/admin/audit-summary?action=CHAT_QUERY`, { headers: { Authorization: `Bearer ${t}` } }); setChatSummary(r.data.data) } catch (_) {} finally { setLoading(false) } };
  const fetchBanner = async (t) => { try { const r = await axios.get(`${API()}/notifications`); setCurrentBanner(r.data.data.banner) } catch (_) {} };
  const toggleIpExpand = async (ip, mode = 'audit') => { if (expandedIp === ip) { setExpandedIp(null); return }; setExpandedIp(ip); setIpLogs([]); setLoadingIpLogs(true); try { const r = await axios.get(`${API()}/admin/audit-logs?ip=${encodeURIComponent(ip)}&limit=10${mode === 'chat' ? '&method=CHAT_QUERY' : ''}`, { headers: { Authorization: `Bearer ${token}` } }); setIpLogs(r.data.data) } catch (_) {} finally { setLoadingIpLogs(false) } };
  const applyFilter = (k, v) => { const n = { ...activeFilters, [k]: v }; if (!v) delete n[k]; setActiveFilters(n); setFilters(p => ({ ...p, [k]: v || '' })); fetchLogs(token, n) };
  const clearFilters = () => { setActiveFilters({}); setFilters({ ip: '', method: '', endpoint: '', startDate: '', endDate: '' }); setAdminActionsOnly(false); fetchLogs(token, {}) };
  const toggleFlag = async () => { const n = !featureFlags.atcoderSubmissions; setFeatureSaving(true); try { await axios.put(`${API()}/admin/feature-flags/atcoder-submissions`, { enabled: n }, { headers: { Authorization: `Bearer ${token}` } }); setFeatureFlags(p => ({ ...p, atcoderSubmissions: n })) } catch (_) {} finally { setFeatureSaving(false) } };
  const handleAddUser = async (e) => { e.preventDefault(); if (!newUser.handle) return; setActionLoading(true); try { await axios.post(`${API()}/admin/users`, { handle: newUser.handle, leetcodeHandle: newUser.leetcodeHandle || undefined, atcoderHandle: newUser.atcoderHandle || undefined, codechefHandle: newUser.codechefHandle || undefined }, { headers: { Authorization: `Bearer ${token}` } }); setNewUser({ handle: '', leetcodeHandle: '', atcoderHandle: '', codechefHandle: '' }); fetchUsers(token) } catch (e) { alert(e.response?.data?.error || 'Error') } finally { setActionLoading(false) } };
  const toggleVisibility = async (h, v) => { if (!confirm(`¿${v ? 'Mostrar' : 'Ocultar'} a ${h}?`)) return; try { await axios.put(`${API()}/admin/users/${h}/visibility`, {}, { headers: { Authorization: `Bearer ${token}` } }); fetchUsers(token) } catch (_) {} };
  const toggleEnabled = async (h, v) => { if (!confirm(`¿${v ? 'Deshabilitar' : 'Habilitar'} tracking para ${h}?`)) return; try { await axios.put(`${API()}/admin/users/${h}/enable`, { enabled: !v }, { headers: { Authorization: `Bearer ${token}` } }); fetchUsers(token) } catch (_) {} };
  const [loadingUsers, setLoadingUsers] = useState({});
  const handleTrack = async (h) => { setLoadingUsers(p => ({ ...p, [h]: true })); try { await axios.post(`${API()}/admin/users/${h}/track`, {}, { headers: { Authorization: `Bearer ${token}` } }); fetchUsers(token) } catch (_) {} finally { setLoadingUsers(p => ({ ...p, [h]: false })) } };
  const handleDelete = async (h) => { if (!confirm(`⚠️ Eliminar a '${h}'?`)) return; try { await axios.delete(`${API()}/admin/users/${h}`, { headers: { Authorization: `Bearer ${token}` } }); fetchUsers(token) } catch (_) {} };
  const setBannerHandler = async (e) => { e.preventDefault(); if (!bannerMsg) return; try { await axios.post(`${API()}/notifications/banner`, { message: bannerMsg, type: bannerType, duration: bannerDuration }, { headers: { Authorization: `Bearer ${token}` } }); setBannerMsg(''); fetchBanner(token) } catch (_) {} };
  const delBanner = async () => { if (!confirm('¿Eliminar banner?')) return; try { await axios.delete(`${API()}/notifications/banner`, { headers: { Authorization: `Bearer ${token}` } }); setCurrentBanner(null) } catch (_) {} };
  const openEditor = (u) => { setEditingUser(u); setNicknameForm({ newHandle: u.handle || '', leetcodeHandle: u.leetcode_handle || '', atcoderHandle: u.atcoder_handle || '', codechefHandle: u.codechef_handle || '' }); setNicknameEditorOpen(true) };
  const closeEditor = () => { setNicknameEditorOpen(false); setEditingUser(null); setNicknameSaving(false) };
  const saveNicknames = async () => { if (!editingUser) return; const cur = editingUser.handle; const d = nicknameForm.newHandle.trim(); if (!d) { alert('Requerido'); return }; setNicknameSaving(true); try { if (d !== cur) await axios.put(`${API()}/admin/users/${cur}/rename`, { newHandle: d }, { headers: { Authorization: `Bearer ${token}` } }); await axios.put(`${API()}/admin/users/${d}/platform-handles`, { leetcodeHandle: nicknameForm.leetcodeHandle.trim() || null, atcoderHandle: nicknameForm.atcoderHandle.trim() || null, codechefHandle: nicknameForm.codechefHandle.trim() || null }, { headers: { Authorization: `Bearer ${token}` } }); fetchUsers(token); closeEditor() } catch (e) { alert(e.response?.data?.error || 'Error'); setNicknameSaving(false) } };
  const filteredUsers = useMemo(() => { const q = userSearch.trim().toLowerCase(); if (!q) return users; return users.filter(u => [u.handle, u.leetcode_handle, u.atcoder_handle, u.codechef_handle].some(v => String(v || '').toLowerCase().includes(q))) }, [users, userSearch]);
  const handleLogin = async (e) => { e.preventDefault(); setLoginError(''); setLoading(true); try { const r = await axios.post(`${API()}/admin/login`, { username, password }); const t = r.data.token; setToken(t); localStorage.setItem('admin_token', t); setIsAuthenticated(true); await fetchUsers(t); await fetchFlags(t) } catch (e) { setLoginError(e.response?.data?.error || 'Error') } finally { setLoading(false) } };

  if (!isAuthenticated && !loading) return (
    <div className="min-h-screen bg-background flex items-center justify-center p-4">
      <div className="w-full max-w-sm rounded-lg border border-border/30 bg-card p-6 shadow-md">
        <div className="flex justify-center mb-4"><div className="flex h-11 w-11 items-center justify-center rounded-lg bg-indigo-100 dark:bg-indigo-900/40"><Lock className="h-5 w-5 text-indigo-600 dark:text-indigo-400" /></div></div>
        <h2 className="text-xl font-bold text-center mb-0.5">Admin Console</h2><p className="text-muted-foreground text-center mb-5 text-sm">Acceso restringido</p>
        <form onSubmit={handleLogin} className="space-y-3">
          <input type="text" placeholder="Usuario" className="w-full border border-border/40 bg-background px-3 py-2 rounded-md text-sm focus:outline-none focus:border-indigo-500/50" value={username} onChange={e => setUsername(e.target.value)} />
          <input type="password" placeholder="Contraseña" className="w-full border border-border/40 bg-background px-3 py-2 rounded-md text-sm focus:outline-none focus:border-indigo-500/50" value={password} onChange={e => setPassword(e.target.value)} />
          {loginError && <p className="text-destructive text-xs text-center">{loginError}</p>}
          <button type="submit" disabled={loading} className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-semibold py-2.5 rounded-md text-sm transition-colors">{loading ? 'Entrando...' : 'Iniciar Sesión'}</button>
        </form>
      </div>
    </div>
  );
  if (loading) return <div className="min-h-screen bg-background flex items-center justify-center text-sm text-muted-foreground">Cargando...</div>;

  const NavBtn = ({ id, icon: Icon, label }) => (<button onClick={() => setView(id)} className={`flex items-center gap-1.5 px-3.5 py-2 rounded-lg text-sm font-medium transition-all ${view === id ? 'bg-indigo-600 text-white shadow-sm' : 'text-muted-foreground hover:text-foreground hover:bg-muted/30'}`}><Icon className="w-4 h-4" />{label}</button>);

  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-50 border-b border-border/30 bg-background/80 backdrop-blur-lg">
        <div className="max-w-7xl mx-auto px-4 flex items-center justify-between h-12"><div className="flex items-center gap-2"><Shield className="w-5 h-5 text-indigo-600 dark:text-indigo-400" /><span className="font-bold text-base">Console</span></div><button onClick={logout} className="text-muted-foreground hover:text-foreground flex items-center gap-1.5 text-sm"><LogOut className="w-4 h-4" />Salir</button></div>
      </nav>
      <main className="max-w-7xl mx-auto px-4 py-5">
        <div className="flex gap-1.5 mb-5 overflow-x-auto pb-1"><NavBtn id="users" icon={Users} label="Usuarios" /><NavBtn id="audit" icon={FileText} label="Auditoría" /><NavBtn id="chat" icon={MessageSquare} label="Chat IA" /><NavBtn id="announcements" icon={Megaphone} label="Anuncios" /></div>

        {view === 'users' && <div className="space-y-4">
          <div className="flex items-center justify-between rounded-lg border border-border/30 bg-card p-3"><div className="flex items-center gap-2"><span className="text-sm font-medium">AtCoder Submissions</span><span className={`inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium ${featureFlags.atcoderSubmissions ? 'bg-emerald-50 text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-400' : 'bg-muted text-muted-foreground'}`}>{featureFlags.atcoderSubmissions ? 'Activo' : 'Desactivado'}</span></div><button onClick={toggleFlag} disabled={featureSaving} className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${featureFlags.atcoderSubmissions ? 'bg-emerald-600 text-white' : 'bg-muted hover:bg-muted/80 text-foreground'}`}>{featureSaving ? '...' : 'Toggle'}</button></div>
          <div className="rounded-lg border border-border/30 bg-card p-3"><div className="flex items-center justify-between"><div><span className="text-sm font-medium">Backfill 2024</span><p className="text-xs text-muted-foreground mt-0.5">Carga todas las submissions desde enero 2024 para todos los usuarios</p></div><button onClick={async () => { if (!confirm('¿Ejecutar backfill? Puede tomar varios minutos.')) return; setBackfilling(true); setBackfillResult(null); try { const r = await axios.post(`${API()}/admin/backfill`, {}, { headers: { Authorization: `Bearer ${token}` } }); setBackfillResult(r.data.data); alert('Backfill completado!') } catch (e) { alert('Error: ' + (e.response?.data?.error || e.message)) } finally { setBackfilling(false) } }} disabled={backfilling} className="px-3 py-1.5 rounded-md bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-medium disabled:opacity-50">{backfilling ? 'Procesando...' : 'Ejecutar Backfill'}</button></div></div>
          <div className="rounded-lg border border-border/30 bg-card p-3"><div className="flex items-center gap-2 mb-3"><UserPlus className="w-5 h-5 text-emerald-500" /><span className="text-sm font-bold">Agregar Usuario</span></div>
            <form onSubmit={handleAddUser} className="space-y-2"><div className="grid gap-2 grid-cols-2 md:grid-cols-4">{[['handle','Handle'],['leetcodeHandle','LeetCode'],['atcoderHandle','AtCoder'],['codechefHandle','CodeChef']].map(([k, label]) => (<input key={k} type="text" placeholder={label} className="border border-border/40 bg-background px-3 py-2 rounded-md text-sm focus:outline-none focus:border-indigo-500/50" value={newUser[k]} onChange={e => setNewUser(p => ({ ...p, [k]: e.target.value }))} />))}</div><button type="submit" disabled={actionLoading} className="bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded-md text-sm font-medium">{actionLoading ? '...' : 'Agregar'}</button></form></div>
          <div className="grid gap-2 grid-cols-3">{[{ label: 'Total', value: users.length }, { label: 'Visibles', value: users.filter(u => !u.is_hidden).length, color: 'text-emerald-600 dark:text-emerald-400' }, { label: 'Tracking', value: users.filter(u => u.enabled).length, color: 'text-indigo-600 dark:text-indigo-400' }].map(s => (<div key={s.label} className="rounded-lg border border-border/30 bg-card p-3"><p className="text-xs uppercase tracking-wider text-muted-foreground font-semibold">{s.label}</p><p className={`text-xl font-bold mt-0.5 ${s.color || ''}`}>{s.value}</p></div>))}</div>
          <div className="rounded-lg border border-border/30 bg-card p-2.5"><div className="flex items-center gap-2"><Search className="h-4 w-4 text-muted-foreground" /><input type="text" value={userSearch} onChange={e => setUserSearch(e.target.value)} placeholder="Buscar..." className="flex-1 bg-transparent text-sm focus:outline-none placeholder:text-muted-foreground/50" /></div></div>
          <div className="rounded-lg border border-border/30 bg-card shadow-sm overflow-hidden">
            <div className="overflow-x-auto"><table className="w-full text-left min-w-[750px]"><thead className="bg-muted/20 text-muted-foreground text-xs uppercase font-semibold"><tr><th className="p-2.5">Handle</th><th className="p-2.5">Estado</th><th className="p-2.5">Última Act.</th><th className="p-2.5 text-right">Acciones</th></tr></thead>
              <tbody className="divide-y divide-border/20">{filteredUsers.map(u => (<tr key={u.handle} className="hover:bg-muted/10 transition-colors">
                <td className="p-2.5"><div className="text-sm font-semibold">{u.handle}</div><div className="flex flex-wrap gap-1 text-xs mt-0.5"><span className="bg-muted/30 border border-border/30 px-1.5 rounded">LC:{u.leetcode_handle || '—'}</span><span className="bg-muted/30 border border-border/30 px-1.5 rounded">AC:{u.atcoder_handle || '—'}</span><span className="bg-muted/30 border border-border/30 px-1.5 rounded">CC:{u.codechef_handle || '—'}</span></div></td>
                <td className="p-2.5">{u.is_hidden ? <span className="bg-red-50 text-red-700 dark:bg-red-900/20 dark:text-red-400 px-2 py-0.5 rounded text-xs font-medium">Oculto</span> : <span className="bg-emerald-50 text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-400 px-2 py-0.5 rounded text-xs font-medium">Visible</span>}{!u.enabled && <span className="ml-1 bg-amber-50 text-amber-700 dark:bg-amber-900/20 dark:text-amber-400 px-2 py-0.5 rounded text-xs font-medium">Pausado</span>}</td>
                <td className="p-2.5 text-sm text-muted-foreground">{u.last_updated ? new Date(u.last_updated).toLocaleString() : '-'}</td>
                <td className="p-2.5"><div className="flex justify-end gap-1">
                  <button onClick={() => toggleVisibility(u.handle, u.is_hidden)} className="p-1.5 rounded border border-border/30 hover:border-indigo-200 dark:hover:border-indigo-700 text-muted-foreground hover:text-foreground transition-colors" title={u.is_hidden ? "Mostrar" : "Ocultar"}>{u.is_hidden ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}</button>
                  <button onClick={() => toggleEnabled(u.handle, u.enabled)} className={`p-1.5 rounded border transition-colors ${u.enabled ? 'bg-emerald-50 border-emerald-200 text-emerald-700 dark:bg-emerald-900/20 dark:border-emerald-800' : 'bg-red-50 border-red-200 text-red-700 dark:bg-red-900/20 dark:border-red-800'}`}>{u.enabled ? <CheckCircle className="w-4 h-4" /> : <XCircle className="w-4 h-4" />}</button>
                  <button onClick={() => handleTrack(u.handle)} disabled={loadingUsers[u.handle]} className="p-1.5 rounded border border-border/30 hover:border-indigo-200 dark:hover:border-indigo-700 text-muted-foreground hover:text-foreground transition-colors"><RefreshCw className={`w-4 h-4 ${loadingUsers[u.handle] ? 'animate-spin' : ''}`} /></button>
                  <button onClick={() => openEditor(u)} className="p-1.5 rounded border border-indigo-200 bg-indigo-50 text-indigo-700 hover:bg-indigo-100 dark:border-indigo-800 dark:bg-indigo-900/20 dark:text-indigo-400"><Edit className="w-4 h-4" /></button>
                  <button onClick={() => handleDelete(u.handle)} className="p-1.5 rounded border border-border/30 hover:border-red-200 dark:hover:border-red-800 text-muted-foreground hover:text-red-600 dark:hover:text-red-400"><Trash2 className="w-4 h-4" /></button>
                </div></td>
              </tr>))}{!filteredUsers.length && <tr><td colSpan="4" className="p-6 text-center text-sm text-muted-foreground">Sin resultados</td></tr>}</tbody></table></div></div>
          {nicknameEditorOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/30 backdrop-blur-sm p-4"><div className="w-full max-w-sm rounded-lg border border-border/30 bg-card p-5 shadow-lg"><h3 className="text-sm font-bold mb-0.5">Editar Nicknames</h3><p className="text-xs text-muted-foreground mb-3">{editingUser?.handle}</p><div className="space-y-2">{['newHandle:Handle principal','leetcodeHandle:LeetCode','atcoderHandle:AtCoder','codechefHandle:CodeChef'].map(f => { const [k, label] = f.split(':'); return <input key={k} type="text" placeholder={label} className="w-full border border-border/40 bg-background px-3 py-2 rounded-md text-sm focus:outline-none focus:border-indigo-500/50" value={nicknameForm[k]} onChange={e => setNicknameForm(p => ({ ...p, [k]: e.target.value }))} />})}</div><div className="flex justify-end gap-2 mt-4"><button onClick={closeEditor} className="px-3 py-2 rounded-md border border-border/30 text-sm font-medium hover:bg-muted/30">Cancelar</button><button onClick={saveNicknames} disabled={nicknameSaving} className="px-3 py-2 rounded-md bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium">{nicknameSaving ? '...' : 'Guardar'}</button></div></div></div>}
        </div>}

        {view === 'audit' && <div className="space-y-3">
          <div className="flex flex-wrap items-center gap-2 rounded-lg border border-border/30 bg-card p-3">
            <div className="flex rounded-md border border-border/30 bg-muted/30 p-0.5">
              <button onClick={() => setAuditViewMode('ip')} className={`px-2.5 py-1.5 rounded-sm text-sm font-medium transition-all ${auditViewMode === 'ip' ? 'bg-white text-foreground shadow-sm dark:bg-primary dark:text-primary-foreground' : 'text-muted-foreground'}`}>Por IP</button>
              <button onClick={() => setAuditViewMode('list')} className={`px-2.5 py-1.5 rounded-sm text-sm font-medium transition-all ${auditViewMode === 'list' ? 'bg-white text-foreground shadow-sm dark:bg-primary dark:text-primary-foreground' : 'text-muted-foreground'}`}>Lista</button>
            </div>
            <label className="flex items-center gap-1.5 text-sm text-muted-foreground cursor-pointer"><input type="checkbox" checked={adminActionsOnly} onChange={e => setAdminActionsOnly(e.target.checked)} className="rounded border-muted-foreground/30 text-indigo-600" />Solo Admin</label>
            <div className="flex items-center gap-1.5 ml-auto"><input type="date" value={filters.startDate} onChange={e => applyFilter('startDate', e.target.value)} className="border border-border/30 bg-background text-sm px-2.5 py-1.5 rounded-md" /><span className="text-xs text-muted-foreground">—</span><input type="date" value={filters.endDate} onChange={e => applyFilter('endDate', e.target.value)} className="border border-border/30 bg-background text-sm px-2.5 py-1.5 rounded-md" /></div>
            {Object.keys(activeFilters).length > 0 && <button onClick={clearFilters} className="text-xs text-muted-foreground hover:text-foreground underline">Limpiar</button>}
          </div>
          {Object.keys(activeFilters).length > 0 && <div className="flex gap-1.5 flex-wrap">{Object.entries(activeFilters).map(([k, v]) => <span key={k} className="bg-indigo-50 text-indigo-700 dark:bg-indigo-900/20 dark:text-indigo-400 border border-indigo-200 dark:border-indigo-800 px-2 py-0.5 rounded text-xs flex items-center gap-0.5">{k}:{v}<button onClick={() => { const n = { ...activeFilters }; delete n[k]; setActiveFilters(n); fetchLogs(token, n) }}><X className="w-3 h-3" /></button></span>)}</div>}
          <div className="rounded-lg border border-border/30 bg-card shadow-sm overflow-hidden">
            <div className="border-b border-border/20 bg-muted/10 p-3 flex justify-between items-center"><span className="text-sm font-bold flex items-center gap-1.5"><Filter className="w-4 h-4 text-indigo-500" />{auditViewMode === 'ip' ? 'Por IP' : 'Detallado'}</span><button onClick={() => auditViewMode === 'ip' ? fetchSummary(token) : fetchLogs(token, activeFilters)} className="flex items-center gap-0.5 text-xs text-indigo-600 hover:text-indigo-700 dark:text-indigo-400"><RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />Refrescar</button></div>
            {auditViewMode === 'ip' ? <div className="divide-y divide-border/20">{auditSummary.filter(i => !activeFilters.ip || i.ip.includes(activeFilters.ip)).map(item => (<div key={item.ip}>
              <div className="flex items-center justify-between p-3 cursor-pointer hover:bg-muted/10 transition-colors" onClick={() => toggleIpExpand(item.ip)}>
                <div className="flex items-center gap-2.5"><div className={`w-2 h-2 rounded-full ${expandedIp === item.ip ? 'bg-indigo-500' : 'bg-muted-foreground/30'}`} /><span className="font-mono text-sm font-bold text-indigo-600 dark:text-indigo-400">{item.ip}</span><span className="text-xs text-muted-foreground">{new Date(item.lastActive).toLocaleString()}</span></div>
                <div className="flex items-center gap-3 text-sm"><span className="font-bold">{item.totalRequests}</span><span className="text-xs text-muted-foreground">req</span>{item.admins?.length > 0 && <span className="font-bold text-emerald-600 dark:text-emerald-400 text-xs">{item.admins.join(',')}</span>}{expandedIp === item.ip ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}</div>
              </div>
              {expandedIp === item.ip && <div className="border-t border-border/20 bg-muted/5 p-3 pl-6">{loadingIpLogs ? <div className="flex items-center gap-1.5 text-sm text-muted-foreground"><div className="h-3 w-3 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent" />Cargando...</div> : <div className="space-y-1">{ipLogs.filter(l => !adminActionsOnly || (!l.action.includes('_REQUEST') && l.action !== 'LOGIN_FAILED')).map(l => (<div key={l.id} className="flex items-center gap-2 text-xs py-1 border-b border-border/10 last:border-0 hover:bg-muted/10 rounded px-1.5"><span className="text-muted-foreground font-mono w-24 shrink-0">{new Date(l.timestamp).toLocaleString()}</span><span className={`font-bold px-1.5 rounded-sm ${l.action.includes('DELETE') ? 'bg-red-50 text-red-700' : l.action.includes('CREATE') ? 'bg-emerald-50 text-emerald-700' : l.action.includes('LOGIN') ? 'bg-indigo-50 text-indigo-700' : 'bg-muted text-muted-foreground'}`}>{l.action}</span><span className="text-muted-foreground truncate flex-1">{l.details?.handle || JSON.stringify(l.details).slice(0, 60)}</span></div>))}</div>}</div>}
            </div>))}{!auditSummary.length && <div className="p-8 text-center text-sm text-muted-foreground">Sin registros.</div>}</div>
            : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="bg-muted/20 text-muted-foreground text-xs uppercase font-semibold"><th className="p-2.5">Timestamp</th><th className="p-2.5">IP</th><th className="p-2.5">Acción</th><th className="p-2.5">Detalle</th></tr></thead><tbody className="divide-y divide-border/10">{logs.filter(l => !adminActionsOnly || (!l.action?.includes('_REQUEST') && l.action !== 'LOGIN_FAILED')).map(l => (<tr key={l.id} className="hover:bg-muted/5"><td className="p-2.5 text-muted-foreground font-mono text-xs">{new Date(l.timestamp).toLocaleString()}</td><td className="p-2.5 font-mono text-indigo-600 dark:text-indigo-400">{l.ip}</td><td className="p-2.5"><span className={`text-xs font-bold px-1.5 py-0.5 rounded-sm ${l.action?.includes('DELETE') ? 'bg-red-50 text-red-700' : l.action?.includes('CREATE') ? 'bg-emerald-50 text-emerald-700' : l.action?.includes('LOGIN') ? 'bg-indigo-50 text-indigo-700' : 'bg-muted text-muted-foreground'}`}>{l.action}</span></td><td className="p-2.5 text-muted-foreground truncate max-w-[250px]">{l.details?.handle || JSON.stringify(l.details).slice(0, 60)}</td></tr>))}{!logs.length && <tr><td colSpan="4" className="p-6 text-center text-muted-foreground">Sin registros.</td></tr>}</tbody></table></div>}
          </div>
        </div>}

        {view === 'chat' && <div className="rounded-lg border border-border/30 bg-card shadow-sm overflow-hidden">
          <div className="border-b border-border/20 bg-muted/10 p-3 flex justify-between items-center"><span className="text-sm font-bold flex items-center gap-1.5"><MessageSquare className="w-4 h-4 text-indigo-500" />Chat IA</span><button onClick={() => fetchChat(token)} className="flex items-center gap-0.5 text-xs text-indigo-600"><RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />Refrescar</button></div>
          {chatSummary.map(item => (<div key={item.ip}><div className="flex items-center justify-between p-3 cursor-pointer hover:bg-muted/10 border-b border-border/10" onClick={() => toggleIpExpand(item.ip, 'chat')}><div className="flex items-center gap-2.5"><div className={`w-2 h-2 rounded-full ${expandedIp === item.ip ? 'bg-indigo-500' : 'bg-muted-foreground/30'}`} /><span className="font-mono text-sm font-bold text-indigo-600 dark:text-indigo-400">{item.ip}</span><span className="text-xs text-muted-foreground">{new Date(item.lastActive).toLocaleString()}</span></div><div className="flex items-center gap-3"><span className="font-bold text-sm">{item.totalRequests}</span><span className="text-xs text-muted-foreground">consultas</span>{expandedIp === item.ip ? <ChevronUp className="w-4 h-4 text-muted-foreground" /> : <ChevronDown className="w-4 h-4 text-muted-foreground" />}</div></div>
          {expandedIp === item.ip && <div className="border-t border-border/10 bg-muted/5 p-3 pl-6">{loadingIpLogs ? <div className="flex items-center gap-1.5 text-sm text-muted-foreground"><div className="h-3 w-3 animate-spin rounded-full border-2 border-indigo-600 border-t-transparent" />Cargando...</div> : <div className="space-y-1.5">{ipLogs.map(l => (<div key={l.id} className="rounded-md border border-border/20 bg-card p-2.5 text-sm"><div className="flex justify-between items-start mb-1"><span className="bg-indigo-50 text-indigo-700 dark:bg-indigo-900/20 dark:text-indigo-400 text-xs px-1.5 py-0.5 rounded border border-indigo-200 dark:border-indigo-800">User: {l.details?.handle || 'Anon'}</span><span className="text-muted-foreground text-xs">{new Date(l.timestamp).toLocaleString()}</span></div><div className="text-foreground/80 whitespace-pre-wrap font-mono text-xs bg-muted/20 p-2 rounded">{l.details?.message || JSON.stringify(l.details)}</div></div>))}</div>}</div>}</div>))}
          {!chatSummary.length && <div className="p-8 text-center text-sm text-muted-foreground"><MessageSquare className="w-8 h-8 mx-auto mb-2 opacity-20" /><p>Sin consultas registradas.</p></div>}
        </div>}

        {view === 'announcements' && <div className="space-y-4">
          <div className="rounded-lg border border-border/30 bg-card p-4"><h3 className="text-sm font-bold mb-3 flex items-center gap-1.5"><Megaphone className="w-5 h-5 text-amber-500" />Banner Global</h3>
            <div className="space-y-3"><input type="text" placeholder="Ej: Mantenimiento programado..." className="w-full border border-border/40 bg-background px-3 py-2.5 rounded-md text-sm focus:outline-none focus:border-indigo-500/50" value={bannerMsg} onChange={e => setBannerMsg(e.target.value)} />
              <div className="grid grid-cols-3 gap-2"><select value={bannerType} onChange={e => setBannerType(e.target.value)} className="border border-border/40 bg-background px-3 py-2 rounded-md text-sm"><option value="info">ℹ️ Info</option><option value="warning">⚠️ Warning</option><option value="error">❌ Error</option></select>
              <input type="number" min="1" value={bannerDuration} onChange={e => setBannerDuration(Number(e.target.value))} className="border border-border/40 bg-background px-3 py-2 rounded-md text-sm" />
              <div className="flex gap-1"><button onClick={setBannerHandler} className="flex-1 bg-indigo-600 hover:bg-indigo-700 text-white px-3 py-2 rounded-md text-sm font-medium">Publicar</button>{currentBanner && <button onClick={delBanner} className="px-3 py-2 rounded-md border border-red-200 text-red-700 hover:bg-red-50 dark:border-red-800 dark:text-red-400 text-sm font-medium">X</button>}</div></div>
              {currentBanner && <div className="rounded-md border border-border/20 bg-muted/10 p-2.5 text-sm"><span className="text-xs uppercase font-semibold text-muted-foreground">Activo:</span><p className="mt-0.5">{currentBanner.message}</p></div>}
            </div>
          </div>
          <CreateNotification token={token} onSuccess={() => {}} />
        </div>}
      </main>
    </div>
  );
}
